test CI/CD to AWS ECR and EC2

diff --git a/server/dockerfile b/server/dockerfile
--- a/server/dockerfile
+++ b/server/dockerfile
@@ -1,38 +1,4 @@
-# FROM node:22.19.0-alpine AS builder
-# WORKDIR /app
-
-# COPY package*.json ./
-# COPY tsconfig.json ./
-
-# RUN npm install
-
-# COPY src ./src
-# COPY workers ./workers
-
-# RUN npm run build
-
-# RUN ls -la dist && test -f dist/src/index.js || (echo "Build failed: dist/src/index.js not found" && exit 1)
-
-# FROM node:22.19.0-alpine
-
-# WORKDIR /app
-
-# COPY package*.json ./
-
-# RUN npm install --only=production
-
-# COPY --from=builder /app/dist ./dist
-
-# COPY firebase.json ./dist/
-
-# EXPOSE 3000
-
-# # CMD ["npm","start"]
-# CMD ["node", "dist/src/index.js"]
-
-
-
-FROM node:22.19.0-alpine
+FROM node:22.19.0-alpine AS builder
 WORKDIR /app
 
 COPY package*.json ./
@@ -42,9 +8,45 @@ RUN npm install
 
 COPY src ./src
 COPY workers ./workers
-COPY firebase.json ./
+
+RUN npm run build
+
+RUN ls -la dist && test -f dist/src/index.js || (echo "Build failed: dist/src/index.js not found" && exit 1)
+
+FROM node:22.19.0-alpine
+
+WORKDIR /app
+
+COPY package*.json ./
+
+RUN npm install --only=production
+
+COPY --from=builder /app/dist ./dist
+
+COPY firebase.json ./dist/
 
 EXPOSE 3000
 
-CMD ["npm","start"]
-# CMD ["node", "dist/src/index.js"]
+CMD ["node", "dist/src/index.js"]
+
+
+
+# FROM node:22.19.0-alpine
+# WORKDIR /app
+
+# COPY package*.json ./
+# COPY tsconfig.json ./
+
+# RUN npm install
+
+# COPY src ./src
+# COPY workers ./workers
+# COPY firebase.json ./
+
+# EXPOSE 3000
+
+# CMD ["npm","start"]
+# CMD ["node", "dist/src/index.js"]khi 
+
+# //npm i -g autocannon
+# autocannon -c 20 -d 10 http://localhost:3000/api
